[tool.poetry]
name = "smirk"
version = "0.1.0"
description = "An experimental pedestrian emergency breaking ADAS."
authors = ["Kasper Socha <kaspersocha@gmail.com>", "Markus Borg <markus.borg@ri.se>"]
readme= "README.md"
repository="https://github.com/RI-SE/smirk"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "~1.19.2"
tensorflow-hub = "^0.11.0"
Pillow = "^8.1.0"
tensorflow = "^2.4.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
flake8-black = "^0.2.1"
flake8-bugbear = "^20.11.1"
mypy = "^0.790"
data-science-types = "^0.2.22"
isort = "^5.7.0"
pre-commit = "^2.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
