scenarios:
  - type: left
    object:
      type: box
      speeds: [4]
      distances_from_car: "${range:10,101,10}"
      distances_from_road: [5]

  - type: right
    object:
      type: box
      speeds: [4]
      distances_from_car: "${range:10,101,10}"
      distances_from_road: [5]
