script: scenario1.script
left_y: 8
right_y: -8
pedestrian:
  models:
    - Pedestrian.zip
  scales: [1]
  speeds: [2]
  angles: '${range:30,150,20}'
  distances: '${range:10,100,10}'
  directions:
    - left
    - right
