scenarios:
  - 
    type: 'left'
    pedestrian:
      speeds: [2]
      angles: "${range:30,151,20}"
      distances_from_car: "${range:10,151,10}"
      distances_from_road: [2]
  - 
    type: 'right'
    pedestrian:
      speeds: [2]
      angles: "${range:30,151,20}"
      distances_from_car: "${range:10,151,10}"
      distances_from_road: [2]
  - 
    type: 'towards'
    pedestrian:
      speeds: [2]
      distances_from_car: [150]
      offsets_from_road_center:  "${range:-3,4,1}"
      max_walking_distance: 140
  - 
    type: 'away'
    pedestrian:
      speeds: [2]
      distances_from_car: [10]
      offsets_from_road_center:  "${range:-3,4,1}"
      max_walking_distance: 140
